// Auth
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const PASSWORD_CHANGED_SECOND = 'PASSWORD_CHANGED_SECOND';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// Favorite
export const FAVORITE_CREATE = 'FAVORITE_CREATE';
export const FAVORITE_CREATE_FAIL = 'FAVORITE_CREATE_FAIL';
export const FAVORITE_FETCH_SUCCESS = 'FAVORITE_FETCH_SUCCESS';
export const FAVORITE_FETCH_FAIL = 'FAVORITE_FETCH_FAIL';
export const FAVORITE_DELETE = 'FAVORITE_DELETE';

// Search
export const SEARCH_CHANGED = 'SEARCH_CHANGED';
export const SEARCH_DEPARTURES = 'SEARCH_DEPARTURES';
export const SEARCH_DEPARTURES_FAIL = 'SEARCH_DEPARTURES_FAIL';
export const SEARCH_BY_GPS = 'SEARCH_BY_GPS';
export const SEARCH_BY_GPS_SUCCESS = 'SEARCH_BY_GPS_SUCCESS';
export const SEARCH_BY_GPS_FAIL = 'SEARCH_BY_GPS_FAIL';
export const SEARCH_BY_GPS_UPDATE = 'SEARCH_BY_GPS_UPDATE';
export const CLR_SEARCH = 'CLR_SEARCH';

// Departures
export const GET_DEPARTURES = 'GET_DEPARTURES';
export const GET_DEPARTURES_FAIL = 'GET_DEPARTURES_FAIL';
export const CLR_DEPARTURES = 'CLR_DEPARTURES';

// Errors
export const ERROR = 'ERROR';
export const CLR_ERROR = 'CLR_ERROR';
