# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'minahallplatser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for minahallplatser
  pod 'Mixpanel'




  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

end
